/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bike_accessories;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author USER
 */
public class SignUp extends javax.swing.JFrame {

    int mousex, mousey;
    Border tf = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.white);

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        ImageIcon i1 = new ImageIcon(getClass().getResource("/dashboard_img/logo.png"));
        setIconImage(i1.getImage());
        nametf.setBorder(tf);
        usernametf.setBorder(tf);
        phonenumbertf.setBorder(tf);
        emailaddresstf.setBorder(tf);
        passwordtf.setBorder(tf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        signupbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        usernametf = new javax.swing.JTextField();
        phonenumbertf = new javax.swing.JTextField();
        emailaddresstf = new javax.swing.JTextField();
        passwordtf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        titlepanel = new javax.swing.JPanel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();
        minimizebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign up to Bikers World");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create New Account ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 220, 60));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(" Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Username :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Phone Number :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Email Address :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 90, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Password :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 90, -1));

        signupbtn.setBackground(new java.awt.Color(255, 255, 255));
        signupbtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        signupbtn.setText("Sign up");
        signupbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        signupbtn.setBorderPainted(false);
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });
        jPanel1.add(signupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 100, 30));

        clearbtn.setBackground(new java.awt.Color(255, 255, 255));
        clearbtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        clearbtn.setBorderPainted(false);
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 100, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Login");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 100, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("-------------------------OR-------------------------");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 275, -1));

        nametf.setBackground(new java.awt.Color(0, 0, 0));
        nametf.setForeground(new java.awt.Color(255, 255, 255));
        nametf.setCaretColor(new java.awt.Color(255, 255, 255));
        nametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametfActionPerformed(evt);
            }
        });
        jPanel1.add(nametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 170, -1));

        usernametf.setBackground(new java.awt.Color(0, 0, 0));
        usernametf.setForeground(new java.awt.Color(255, 255, 255));
        usernametf.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(usernametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 170, -1));

        phonenumbertf.setBackground(new java.awt.Color(0, 0, 0));
        phonenumbertf.setForeground(new java.awt.Color(255, 255, 255));
        phonenumbertf.setCaretColor(new java.awt.Color(255, 255, 255));
        phonenumbertf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonenumbertfKeyPressed(evt);
            }
        });
        jPanel1.add(phonenumbertf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 170, -1));

        emailaddresstf.setBackground(new java.awt.Color(0, 0, 0));
        emailaddresstf.setForeground(new java.awt.Color(255, 255, 255));
        emailaddresstf.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(emailaddresstf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 170, -1));

        passwordtf.setBackground(new java.awt.Color(0, 0, 0));
        passwordtf.setForeground(new java.awt.Color(255, 255, 255));
        passwordtf.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(passwordtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 170, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Already have an existing account?");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard_img/signupimg.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 640, 500));

        titlepanel.setBackground(new java.awt.Color(255, 255, 255));
        titlepanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlepanelMouseDragged(evt);
            }
        });
        titlepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlepanelMousePressed(evt);
            }
        });

        jLabel95.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel95.setText("Sign up ");

        jLabel96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard_img/logo.png"))); // NOI18N

        closebtn.setBackground(new java.awt.Color(255, 255, 255));
        closebtn.setText("X");
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closebtnMouseExited(evt);
            }
        });
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });

        minimizebtn.setBackground(new java.awt.Color(255, 255, 255));
        minimizebtn.setText("-");
        minimizebtn.setFocusPainted(false);
        minimizebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizebtnMouseExited(evt);
            }
        });
        minimizebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout titlepanelLayout = new javax.swing.GroupLayout(titlepanel);
        titlepanel.setLayout(titlepanelLayout);
        titlepanelLayout.setHorizontalGroup(
            titlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlepanelLayout.createSequentialGroup()
                .addComponent(jLabel96)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 459, Short.MAX_VALUE)
                .addComponent(minimizebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closebtn))
        );
        titlepanelLayout.setVerticalGroup(
            titlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlepanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(titlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel96, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimizebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(titlepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 530));

        setSize(new java.awt.Dimension(640, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
        String name, user, phone, email, pass;
        name = nametf.getText();
        user = usernametf.getText();
        phone = phonenumbertf.getText();
        email = emailaddresstf.getText();
        pass = passwordtf.getText();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bike_accessories?zeroDateTimeBehavior=convertToNull", "root", "");
            Statement st = con.createStatement();
            st.executeUpdate("insert into register values('" + name + "','" + user + "','" + phone + "','" + email + "','" + pass + "')");
        } catch (SQLException e) {
            e.printStackTrace();
        }
        if (nametf.getText().isEmpty() || usernametf.getText().isEmpty() || phonenumbertf.getText().isEmpty() || emailaddresstf.getText().isEmpty() || passwordtf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Account Creation Failed");
        } else {
            Main_Frame main = new Main_Frame();
            main.usernamelbl.setText(usernametf.getText());
            JOptionPane.showMessageDialog(null, "Account Created Successfully");
            dispose();
            main.setVisible(true);
        }
    }//GEN-LAST:event_signupbtnActionPerformed

    private void nametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametfActionPerformed

    private void closebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseEntered
        closebtn.setBackground(Color.red);
        closebtn.setForeground(Color.white);
    }//GEN-LAST:event_closebtnMouseEntered

    private void closebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseExited
        closebtn.setBackground(Color.white);
        closebtn.setForeground(Color.black);
    }//GEN-LAST:event_closebtnMouseExited

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void minimizebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizebtnMouseEntered
        minimizebtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_minimizebtnMouseEntered

    private void minimizebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizebtnMouseExited
        minimizebtn.setBackground(Color.white);
    }//GEN-LAST:event_minimizebtnMouseExited

    private void minimizebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizebtnActionPerformed
        setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizebtnActionPerformed

    private void titlepanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlepanelMouseDragged
        this.setLocation(this.getX() + evt.getX() - mousex, this.getY() + evt.getY() - mousey);
    }//GEN-LAST:event_titlepanelMouseDragged

    private void titlepanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlepanelMousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_titlepanelMousePressed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearbtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void phonenumbertfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenumbertfKeyPressed
        String mobile = phonenumbertf.getText();
        int length = mobile.length();
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            if (length < 10) {
                phonenumbertf.setEditable(true);
            } else {
                phonenumbertf.setEditable(false);
            }
        } else if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
            phonenumbertf.setEditable(true);
        } else {
            phonenumbertf.setEditable(false);
        }
    }//GEN-LAST:event_phonenumbertfKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton closebtn;
    private javax.swing.JTextField emailaddresstf;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minimizebtn;
    private javax.swing.JTextField nametf;
    private javax.swing.JTextField passwordtf;
    private javax.swing.JTextField phonenumbertf;
    private javax.swing.JButton signupbtn;
    private javax.swing.JPanel titlepanel;
    private javax.swing.JTextField usernametf;
    // End of variables declaration//GEN-END:variables
}
